### ISSUE TITLE
Richiesta feature

### ISSUE THREAD

**Issue by CavoElettrico69** [EtanoloYT/gfy#1]
Implementare la possibilità di stampare parole e di salvare una parola come variabile, così posso insultare la persona che esegue il codice.

**Comment by EtanoloYT** [comment]
Easy, se ti serve anche modificare stringhe etc apri una seconda issue

**Comment by CavoElettrico69** [comment]
Per ora va bene così, ballo del godo

**Comment by CavoElettrico69** [comment]
simo come cazzo funziona non hai spiegato un cazzo

**Comment by EtanoloYT** [comment]
Ho fixato:
set frase "cavo sei un gamer"
print frase

oppure
set frase 'cavo wow epico'
print frase

**Comment by CavoElettrico69** [comment]
Perfetto
